apiVersion: v1
kind: Pod
metadata:
  name: env
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: course
      valueFrom: 
        configMapRef:
          name: course-config  
          key:  course
    - name: duration
      valueFrom:
        configMapRef:
          name: course-config  
          key:  duration

