apiVersion: v1
kind: Pod
metadata:
  name: probe
spec:
  containers:
  - name: nginx
    image: nginx
    livenessProbe:
       tcpSocket:
        path: /
        port: 8080
      initialDelaySeconds: 3
      periodSeconds: 5