apiVersion: v1
kind: Pod
metadata:
  name: resources
spec:
  containers:
    - name: nginx
      image: nginx
      resourcess: 
        requests: 
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu:  "500m"
            
          

      name: stress
      command: ["sleep", "1800"]
       