apiVersion: v1
kind: Pod
metadata:
  name: stress
spec:
  containers:
    - name: nginx
      image:  ashokg1992/stress
      imagePullPolicy: Always
      name: stress
      command: ["sleep", "1800"]
       