apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
  - name: nginx
    image: nginx
     imagePullPolicy: Always
    env:
      - name: USERNAME   #anyname
        valueFrom:
          secretKeyRef:
            name: mysecret          #secret file check and name give as it is 
            key: username              # username: YXNob2s=  check  this in secretfile 
      - name: PASSWORD                #anyname
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: password                    #  passwaord: YXNob2sxMjM=   check  this in secretfile 